
project_id = "uqqsgmwkvslaomzxptnp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[functions.twilio-webhook]
verify_jwt = false

[functions.add-note]
verify_jwt = true

[functions.add-url]
verify_jwt = true

[functions.get-public-feed]
verify_jwt = false

[functions.get-comments]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false

[functions.create-trial-subscription]
verify_jwt = true

[functions.quick-pdf-summary]
verify_jwt = true

[db]
port = 54322

[storage]
enabled = true
file_size_limit = "50MiB"
