// Regenerates every raster/derived brand asset from the vector sources in this directory.
//   node brand/build.mjs          (run from the repo root; needs Google Chrome + macOS sips)
// Sources: brand/stash-wordmark.svg (the "Stash" wordmark, no strokes), brand/stash-s.svg (its
// first S) and brand/stash-a4.svg (the A/4 symbol, DESIGN-v2).
// Derived:
//   web (DESIGN-v2, from brand/web-icon-src.html): public/favicon.svg + .ico, favicon-16/32,
//     apple-touch-icon, icon-192/512 (PWA);
//   apps (from brand/icon-src.html, the S, until those surfaces move to v2): Chrome-extension
//     icons, iOS AppIcon (app + share extension) and the onboarding tile;
//   plus the iOS wordmark imagesets.
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const root = process.cwd();
const CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const SOURCES = {
  web: path.join(root, 'brand', 'web-icon-src.html'),
  app: path.join(root, 'brand', 'icon-src.html'),
};
const a4Path = fs.readFileSync(path.join(root, 'brand', 'stash-a4.svg'), 'utf8').match(/ d="([^"]+)"/)[1];
const wordmark = fs.readFileSync(path.join(root, 'brand', 'stash-wordmark.svg'), 'utf8');

// --- favicon.svg: the web-icon-src.html favicon cut as a standalone SVG — the A/4 at 68.75% of a
//     charcoal tile with 22% corners (the ST4SH kit's favicon composition) ---
const TILE = 1024, GLYPH_W = 660, GLYPH_H = 700, PCT = 0.6875;
const k = (TILE * PCT) / GLYPH_H;
const tx = ((TILE - GLYPH_W * k) / 2).toFixed(2), ty = ((TILE + GLYPH_H * k) / 2).toFixed(2);
fs.writeFileSync(path.join(root, 'public', 'favicon.svg'),
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${TILE} ${TILE}">
  <!-- Generated by brand/build.mjs from brand/stash-a4.svg — the A/4 symbol in warm white #f3f2ee
       on a charcoal #171b1a tile (DESIGN-v2; see brand/web-icon-src.html). -->
  <rect width="${TILE}" height="${TILE}" rx="${(TILE * 0.22).toFixed(2)}" fill="#171b1a"/>
  <path fill="#f3f2ee" fill-rule="evenodd" transform="translate(${tx},${ty}) scale(${k.toFixed(5)},${(-k).toFixed(5)})" d="${a4Path}"/>
</svg>
`);

// --- iOS wordmark imagesets (template-rendered, so the fill colour is irrelevant) ---
for (const p of ['ios/Stash/Assets.xcassets/StashWordmark.imageset/stash-wordmark.svg',
                 'ios/StashShareExtension/Assets.xcassets/StashWordmark.imageset/stash-wordmark.svg']) {
  fs.writeFileSync(path.join(root, p), wordmark);
}

// --- raster icons: Chrome renders the vector at the exact target size (no downscaling) ---
const tmp = fs.mkdtempSync('/tmp/stash-icons-');
function render(source, size, rounded) {
  const key = `${source}-${size}${rounded ? 'r' : ''}`;
  const out = path.join(tmp, `${key}.png`);
  if (fs.existsSync(out)) return out;
  const win = 1024; // headless Chrome enforces a minimum window; the tile is centred, crop after
  const raw = path.join(tmp, `raw-${key}.png`);
  execFileSync(CHROME, ['--headless', '--disable-gpu', '--hide-scrollbars', '--default-background-color=00000000',
    `--screenshot=${raw}`, `--window-size=${win},${win}`, `file://${SOURCES[source]}#size=${size}${rounded ? '&rounded' : ''}`],
    { stdio: 'ignore' });
  if (win !== size) execFileSync('sips', ['-c', String(size), String(size), raw, '--out', out], { stdio: 'ignore' });
  else fs.copyFileSync(raw, out);
  return out;
}
const targets = [
  ['public/favicon-16.png', 'web', 16, true], ['public/favicon-32.png', 'web', 32, true],
  ['public/apple-touch-icon.png', 'web', 180, false], ['public/icon-192.png', 'web', 192, false], ['public/icon-512.png', 'web', 512, false],
  ['extension/icons/icon16.png', 'app', 16, true], ['extension/icons/icon32.png', 'app', 32, true],
  ['extension/icons/icon48.png', 'app', 48, true], ['extension/icons/icon128.png', 'app', 128, true],
  ['ios/Stash/Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png', 'app', 1024, false],
  ['ios/StashShareExtension/Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png', 'app', 1024, false],
  ['ios/Stash/Assets.xcassets/onboarding.stashTile.imageset/onboarding.stashTile@2x.png', 'app', 180, false],
  ['ios/Stash/Assets.xcassets/onboarding.stashTile.imageset/onboarding.stashTile@3x.png', 'app', 270, false],
];
for (const [dest, source, size, rounded] of targets) {
  fs.copyFileSync(render(source, size, rounded), path.join(root, dest));
  console.log('wrote', dest);
}

// --- favicon.ico: PNG-compressed entries at 16/32/48 (every modern browser/OS reads these) ---
const entries = [16, 32, 48].map(s => fs.readFileSync(render('web', s, true)));
const header = Buffer.alloc(6); header.writeUInt16LE(0, 0); header.writeUInt16LE(1, 2); header.writeUInt16LE(entries.length, 4);
let offset = 6 + 16 * entries.length;
const dir = entries.map((buf, i) => {
  const s = [16, 32, 48][i], e = Buffer.alloc(16);
  e.writeUInt8(s, 0); e.writeUInt8(s, 1); e.writeUInt8(0, 2); e.writeUInt8(0, 3);
  e.writeUInt16LE(1, 4); e.writeUInt16LE(32, 6); e.writeUInt32LE(buf.length, 8); e.writeUInt32LE(offset, 12);
  offset += buf.length; return e;
});
fs.writeFileSync(path.join(root, 'public', 'favicon.ico'), Buffer.concat([header, ...dir, ...entries]));
console.log('wrote public/favicon.ico');
fs.rmSync(tmp, { recursive: true, force: true });
