// Regenerates every raster/derived brand asset from the two vector sources in this directory.
//   node brand/build.mjs          (run from the repo root; needs Google Chrome + macOS sips)
// Sources: brand/stash-wordmark.svg (the "Stash" wordmark, no strokes) and brand/stash-s.svg
// (its first S). Derived: public/favicon.svg, the iOS wordmark imagesets, and all icon PNGs/ICO
// (web favicons + PWA icons, Chrome-extension icons, iOS AppIcon + onboarding tile).
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const root = process.cwd();
const CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const srcHtml = path.join(root, 'brand', 'icon-src.html');
const sPath = fs.readFileSync(path.join(root, 'brand', 'stash-s.svg'), 'utf8').match(/ d="([^"]+)"/)[1];
const wordmark = fs.readFileSync(path.join(root, 'brand', 'stash-wordmark.svg'), 'utf8');

// --- favicon.svg: same composition as icon-src.html, rounded 20%, as a standalone SVG ---
const S_W = 222.77, S_H = 294.3, TILE = 1024, PCT = 0.62;
const k = (TILE * PCT) / S_H, sw = S_W * k, sh = S_H * k;
const tx = ((TILE - sw) / 2).toFixed(2), ty = ((TILE - sh) / 2).toFixed(2);
fs.writeFileSync(path.join(root, 'public', 'favicon.svg'),
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${TILE} ${TILE}">
  <!-- Generated by brand/build.mjs from brand/stash-s.svg — the wordmark's first S in white
       #ffffff on the purple→blue page-wash stops (see brand/icon-src.html). -->
  <defs>
    <linearGradient id="g" x1="0" y1="1" x2="1" y2="0">
      <stop offset="0" stop-color="#764ba2"/>
      <stop offset="0.3333" stop-color="#9d5fd8"/>
      <stop offset="0.6667" stop-color="#667eea"/>
      <stop offset="1" stop-color="#4facfe"/>
    </linearGradient>
  </defs>
  <rect width="${TILE}" height="${TILE}" rx="${TILE * 0.2}" fill="url(#g)"/>
  <path fill="#ffffff" transform="translate(${tx},${ty}) scale(${k.toFixed(5)})" d="${sPath}"/>
</svg>
`);

// --- iOS wordmark imagesets (template-rendered, so the fill colour is irrelevant) ---
for (const p of ['ios/Stash/Assets.xcassets/StashWordmark.imageset/stash-wordmark.svg',
                 'ios/StashShareExtension/Assets.xcassets/StashWordmark.imageset/stash-wordmark.svg']) {
  fs.writeFileSync(path.join(root, p), wordmark);
}

// --- raster icons: Chrome renders the vector at the exact target size (no downscaling) ---
const tmp = fs.mkdtempSync('/tmp/stash-icons-');
function render(size, rounded) {
  const out = path.join(tmp, `${size}${rounded ? 'r' : ''}.png`);
  if (fs.existsSync(out)) return out;
  const win = 1024; // headless Chrome enforces a minimum window; the tile is centred, crop after
  const raw = path.join(tmp, `raw-${size}${rounded ? 'r' : ''}.png`);
  execFileSync(CHROME, ['--headless', '--disable-gpu', '--hide-scrollbars', '--default-background-color=00000000',
    `--screenshot=${raw}`, `--window-size=${win},${win}`, `file://${srcHtml}#size=${size}${rounded ? '&rounded' : ''}`],
    { stdio: 'ignore' });
  if (win !== size) execFileSync('sips', ['-c', String(size), String(size), raw, '--out', out], { stdio: 'ignore' });
  else fs.copyFileSync(raw, out);
  return out;
}
const targets = [
  ['public/favicon-16.png', 16, true], ['public/favicon-32.png', 32, true],
  ['public/apple-touch-icon.png', 180, false], ['public/icon-192.png', 192, false], ['public/icon-512.png', 512, false],
  ['extension/icons/icon16.png', 16, true], ['extension/icons/icon32.png', 32, true],
  ['extension/icons/icon48.png', 48, true], ['extension/icons/icon128.png', 128, true],
  ['ios/Stash/Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png', 1024, false],
  ['ios/StashShareExtension/Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png', 1024, false],
  ['ios/Stash/Assets.xcassets/onboarding.stashTile.imageset/onboarding.stashTile@2x.png', 180, false],
  ['ios/Stash/Assets.xcassets/onboarding.stashTile.imageset/onboarding.stashTile@3x.png', 270, false],
];
for (const [dest, size, rounded] of targets) {
  fs.copyFileSync(render(size, rounded), path.join(root, dest));
  console.log('wrote', dest);
}

// --- favicon.ico: PNG-compressed entries at 16/32/48 (every modern browser/OS reads these) ---
const entries = [16, 32, 48].map(s => fs.readFileSync(render(s, true)));
const header = Buffer.alloc(6); header.writeUInt16LE(0, 0); header.writeUInt16LE(1, 2); header.writeUInt16LE(entries.length, 4);
let offset = 6 + 16 * entries.length;
const dir = entries.map((buf, i) => {
  const s = [16, 32, 48][i], e = Buffer.alloc(16);
  e.writeUInt8(s, 0); e.writeUInt8(s, 1); e.writeUInt8(0, 2); e.writeUInt8(0, 3);
  e.writeUInt16LE(1, 4); e.writeUInt16LE(32, 6); e.writeUInt32LE(buf.length, 8); e.writeUInt32LE(offset, 12);
  offset += buf.length; return e;
});
fs.writeFileSync(path.join(root, 'public', 'favicon.ico'), Buffer.concat([header, ...dir, ...entries]));
console.log('wrote public/favicon.ico');
fs.rmSync(tmp, { recursive: true, force: true });
