// @vitest-environment node
import fs from 'node:fs';
import path from 'node:path';

/**
 * What ships at gostash.it/, /extension, /connect and /iphone (published from the homepage
 * prototype by scripts/publish-site.mjs and committed): no prototype leftovers, every /site asset
 * it names published, the release stamps the extension publisher rewrites, and the way into the app.
 */
const ROOT = path.resolve(__dirname, '..');
const PUBLIC = path.join(ROOT, 'public');
const read = (rel: string) => fs.readFileSync(path.join(PUBLIC, rel), 'utf8');
const pages = ['site/home.html', 'extension/index.html', 'connect/index.html', 'iphone/index.html'];
const scripts = fs.readdirSync(path.join(PUBLIC, 'site/js')).map((name) => `site/js/${name}`);
const generatedHeader = (text: string) =>
  text.replace(/Generated by scripts\/publish-site\.mjs from [^.]+\. Edit the prototype and re-run; don’t edit this file\./g, '');

describe('the published marketing site', () => {
  it.each([...pages, 'site/style.css', ...scripts])('%s carries nothing prototype-only', (rel) => {
    const text = generatedHeader(read(rel));
    for (const leftover of ['2026-10-06-stashe-homepage', 'src/assets', 'prototype: not sent', 'data-notify', 'class="review"', 'exploration v0']) {
      expect(text, leftover).not.toContain(leftover);
    }
  });

  it.each([...pages, 'site/style.css', ...scripts])('%s names only /site assets that were published', (rel) => {
    for (const [, ref] of read(rel).matchAll(/["'(](\/site\/[^"')?#\s]+)/g)) {
      expect(fs.existsSync(path.join(PUBLIC, ref)), ref).toBe(true);
    }
  });

  it.each(pages)('%s has a real title, description, icons and social card', (rel) => {
    const html = read(rel);
    expect(html).toMatch(/<title>[^<]*Stash[^<]*<\/title>/);
    expect(html).toMatch(/<meta name="description" content="[^"]{40,}">/);
    expect(html).toContain('<link rel="icon" href="/favicon.svg?v=a4" type="image/svg+xml">');
    expect(html).toContain('<meta property="og:image" content="https://www.gostash.it/og-v2.jpg">');
    expect(fs.existsSync(path.join(PUBLIC, 'og-v2.jpg'))).toBe(true);
  });

  it('keeps the stamps extension/scripts/publish-hosted-zip.sh rewrites on every release', () => {
    const html = read('extension/index.html');
    expect(html).toMatch(/<span data-version>[0-9.]+<\/span>/);
    expect(html).toMatch(/<span data-size>[0-9]+ KB<\/span>/);
  });

  it('opens sign-up from Get Stash and the app from Sign in, and links the pages on clean URLs', () => {
    const home = read('site/home.html');
    expect(home.match(/href="\/auth\?mode=signup">Get Stash/g)).toHaveLength(2);
    expect(home).not.toContain('href="#start"');
    const site = read('site/js/site.js');
    expect(site).toContain("app('/auth')");
    expect(site).toContain('"extension.html":"/extension"');
    expect(site).toContain('"mcp.html":"/connect"');
    expect(site).toContain('"iphone.html":"/iphone"');
  });

  it('says plainly how to join the iPhone beta instead of a sign-up with nothing behind it', () => {
    expect(read('iphone/index.html')).toContain('Want to try it? <a href="mailto:');
    expect(read('site/js/site.js')).toContain('Want to try it? <a href="mailto:');
  });
});
