#!/usr/bin/env node
/**
 * Publish the homepage prototype as the live marketing site:
 *   gostash.it/            the homepage        public/site/home.html (made / by place-site-home.mjs)
 *   gostash.it/extension   Stash it for Chrome public/extension/index.html
 *   gostash.it/connect     connect your AI     public/connect/index.html
 *   gostash.it/iphone      Stash for iPhone    public/iphone/index.html
 *   gostash.it/contact     write to us         public/contact/index.html
 *   gostash.it/terms       terms of service    public/terms/index.html
 *   gostash.it/privacy     privacy policy      public/privacy/index.html
 *   gostash.it/site/…      the pages' CSS, scripts, images and fonts
 *
 *   node scripts/publish-site.mjs
 *
 * One source: docs/superpowers/prototypes/2026-10-06-stashe-homepage(.html) is where the site is
 * designed and reviewed. This turns it into static files: absolute asset paths, production head
 * tags, no design-history comments, no review panel, the page links on clean URLs, sign-up behind
 * "Get Stash", and an honest beta line where the unwired "Notify me" form was. Every rewrite
 * asserts its anchor and the output is checked for prototype leftovers, so a prototype change that
 * moves something fails here, loudly, rather than shipping. Commit what it writes. Never edit the
 * outputs by hand: edit the prototype and re-run. The extension page keeps the version and size
 * stamps that extension/scripts/publish-hosted-zip.sh rewrites on every release.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PROTO = path.join(ROOT, 'docs/superpowers/prototypes');
const FOLDER = path.join(PROTO, '2026-10-06-stashe-homepage');
const PUBLIC = path.join(ROOT, 'public');
const SITE = path.join(PUBLIC, 'site');

const ORIGIN = 'https://www.gostash.it';
const PAGES = { 'extension.html': '/extension', 'mcp.html': '/connect', 'iphone.html': '/iphone', 'contact.html': '/contact', 'terms.html': '/terms', 'privacy.html': '/privacy' };
const BETA_MAIL = 'mailto:hello@gostash.it?subject=Stash%20for%20iPhone%20beta';
const GENERATED = '<!-- Generated by scripts/publish-site.mjs from docs/superpowers/prototypes/2026-10-06-stashe-homepage. Edit the prototype and re-run; don’t edit this file. -->';

const fail = (message) => {
  console.error(`publish-site: ${message}`);
  process.exit(1);
};

/** Replace `from` with `to`, exactly `count` times (or at least once with count 'some') */
const swap = (text, from, to, count = 1, where = '') => {
  const found = text.split(from).length - 1;
  if (count === 'some' ? found === 0 : found !== count) {
    fail(`expected ${count} of ${JSON.stringify(from.slice(0, 80))} in ${where}, found ${found}`);
  }
  return text.split(from).join(to);
};

/** Replace the one match of `re`, failing if there isn't exactly one */
const swapRe = (text, re, to, where) => {
  const found = text.match(new RegExp(re.source, re.flags.includes('g') ? re.flags : `${re.flags}g`)) ?? [];
  if (found.length !== 1) fail(`expected one match of ${re} in ${where}, found ${found.length}`);
  return text.replace(re, to);
};

const read = (file) => fs.readFileSync(file, 'utf8');
const write = (file, text) => {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, text);
};
const copyDir = (from, to, keep = () => true) => {
  fs.mkdirSync(to, { recursive: true });
  for (const name of fs.readdirSync(from)) {
    if (!keep(name)) continue;
    fs.copyFileSync(path.join(from, name), path.join(to, name));
  }
};

const icons = `<link rel="icon" href="/favicon.ico?v=a4" sizes="48x48">
<link rel="icon" href="/favicon.svg?v=a4" type="image/svg+xml">
<link rel="icon" href="/favicon-32.png?v=a4" type="image/png" sizes="32x32">
<link rel="apple-touch-icon" href="/apple-touch-icon.png?v=a4">
<link rel="manifest" href="/site.webmanifest?v=a4">`;

const social = ({ url, title, description }) => `<link rel="canonical" href="${ORIGIN}${url}">
<meta property="og:type" content="website">
<meta property="og:url" content="${ORIGIN}${url}">
<meta property="og:title" content="${title}">
<meta property="og:description" content="${description}">
<meta property="og:image" content="${ORIGIN}/og-v2.jpg">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="Stash: save it fast, find it when you need it.">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image" content="${ORIGIN}/og-v2.jpg">`;

const attr = (html, name) => {
  const match = html.match(new RegExp(`<meta name="${name}" content="([^"]*)">`));
  return match ? match[1] : null;
};

/** Head, comments and the shared page-level rewrites */
const finishPage = (html, { where, url, title, description, favicon }) => {
  html = html.replace(/<!--[\s\S]*?-->\n?/g, '');
  html = html.replace(/<title>[^<]*<\/title>/, `<title>${title}</title>`);
  if (description) {
    html = html.replace(/<meta name="description" content="[^"]*">/, `<meta name="description" content="${description}">`);
  }
  const desc = attr(html, 'description');
  if (!desc) fail(`no description in ${where}`);
  html = swap(html, favicon, `${icons}\n${social({ url, title, description: desc })}`, 1, where);
  html = swap(html, '<!doctype html>', `<!doctype html>\n${GENERATED}`, 1, where);
  return html;
};

// ---- the homepage --------------------------------------------------------------------------------
let home = read(path.join(PROTO, '2026-10-06-stashe-homepage.html'));
const W = 'the homepage';
for (const [file, url] of Object.entries(PAGES)) {
  home = home.split(`href="2026-10-06-stashe-homepage/${file}"`).join(`href="${url}"`);
}
// Get Stash opens sign-up (in the prototype both buttons point at the closing section)
home = swap(home, '<a class="btn btn-ink" href="#start">Get Stash</a>', '<a class="btn btn-ink" href="/auth?mode=signup">Get Stash</a>', 2, W);
home = swap(home, '../../../src/assets/landing/', '/site/landing/', 'some', W);
home = swap(home, '2026-10-06-stashe-homepage/', '/site/', 'some', W);
home = finishPage(home, {
  where: W,
  url: '/',
  title: 'Stash — save it fast, find it when you need it',
  description:
    'Save anything in one tap: a link, a screenshot, a TikTok, a voice note. Stash reads it and gathers the background, so you can find it when you need it, or ask your AI.',
  favicon: '<link rel="icon" href="/site/logo/favicon.svg" type="image/svg+xml">',
});
write(path.join(SITE, 'home.html'), home);

// ---- the pages beside it -------------------------------------------------------------------------
const pageHtml = (name, { url, title, edit = (html) => html }) => {
  let html = read(path.join(FOLDER, name));
  html = swap(html, 'href="style.css"', 'href="/site/style.css"', 1, name);
  html = swap(html, 'src="js/', 'src="/site/js/', 'some', name);
  html = html.split('src="img/').join('src="/site/img/');
  html = edit(html);
  return finishPage(html, { where: name, url, title, favicon: '<link rel="icon" href="logo/favicon.svg" type="image/svg+xml">' });
};

// Stash it for Chrome: the version and size become the stamps publish-hosted-zip.sh rewrites
const manifest = JSON.parse(read(path.join(ROOT, 'extension/manifest.json')));
const zipKb = Math.ceil(fs.statSync(path.join(PUBLIC, 'stash-it-extension.zip')).size / 1024);
const extension = pageHtml('extension.html', {
  url: '/extension',
  title: 'Install Stash it in Chrome · Stash',
  edit: (html) =>
    swapRe(
      html,
      /<small>version [0-9.]+, [0-9]+ KB<\/small>/,
      `<small>version <span data-version>${manifest.version}</span>, <span data-size>${zipKb} KB</span></small>`,
      'extension.html',
    ),
});
write(path.join(PUBLIC, 'extension/index.html'), extension);

write(path.join(PUBLIC, 'connect/index.html'), pageHtml('mcp.html', { url: '/connect', title: 'Connect your AI to Stash (MCP) · Stash' }));

// Stash for iPhone: no list sits behind "Notify me" yet, so the page says what's true instead
write(
  path.join(PUBLIC, 'iphone/index.html'),
  pageHtml('iphone.html', {
    url: '/iphone',
    title: 'Stash for iPhone · Stash',
    edit: (html) =>
      swapRe(
        html,
        /\s*<form class="notify is-big" data-notify[\s\S]*?<\/form>\s*<p class="page-note">[^<]*<\/p>/,
        `\n        <p class="page-note">It’s in beta now. Want to try it? <a href="${BETA_MAIL}">Email us</a> and we’ll set you up.</p>`,
        'iphone.html',
      ),
  }),
);

// Contact, terms and privacy: the legal text is the policy itself, so nothing is rewritten but the
// links to the pages beside them
const legalLinks = (html) => {
  for (const [file, url] of Object.entries(PAGES)) html = html.split(`href="${file}"`).join(`href="${url}"`);
  return html;
};
write(path.join(PUBLIC, 'contact/index.html'), pageHtml('contact.html', { url: '/contact', title: 'Contact · Stash', edit: legalLinks }));
write(path.join(PUBLIC, 'terms/index.html'), pageHtml('terms.html', { url: '/terms', title: 'Terms · Stash' }));
write(path.join(PUBLIC, 'privacy/index.html'), pageHtml('privacy.html', { url: '/privacy', title: 'Privacy · Stash' }));

// ---- assets --------------------------------------------------------------------------------------
let css = read(path.join(FOLDER, 'style.css'));
css = swap(css, 'url(../../../../src/assets/fonts/', 'url(/site/fonts/', 'some', 'style.css');
css = swap(css, 'url(../../../../src/assets/landing/', 'url(/site/landing/', 'some', 'style.css');
// The stylesheet's comments are the design notes (version history and all); the site needn't serve them
css = `/* ${GENERATED.slice(5, -4)} */\n${css.replace(/\/\*[\s\S]*?\*\/\n?/g, '')}`;
write(path.join(SITE, 'style.css'), css);

for (const name of fs.readdirSync(path.join(FOLDER, 'js'))) {
  let js = read(path.join(FOLDER, 'js', name));
  js = js.split("'../../../src/assets/landing/'").join("'/site/landing/'");
  js = js.split("'2026-10-06-stashe-homepage/img/'").join("'/site/img/'");
  js = js.split('url(2026-10-06-stashe-homepage/img/').join('url(/site/img/');
  if (name === 'site.js') {
    const S = 'site.js';
    js = swap(js, "const homeUrl = new URL('../2026-10-06-stashe-homepage.html', folder).href;", "const homeUrl = '/';", 1, S);
    js = swap(
      js,
      'const pageUrl = (name) => new URL(name, folder).href;',
      `const pageUrl = (name) => (${JSON.stringify(PAGES)})[name] || new URL(name, folder).href;`,
      1,
      S,
    );
    // The prototype's review panel (version label, lime/violet switch) stays in the prototype
    js = swapRe(js, /\n  const label = \{[\s\S]*?<\/aside>`\);\n/, '\n', S);
    js = swapRe(
      js,
      /<p>In beta now\. Get one email, the day it’s on the App Store\.<\/p>\s*<form class="notify" data-notify[\s\S]*?<\/form>/,
      `<p>In beta now. Want to try it? <a href="${BETA_MAIL}">Email us</a>.</p>`,
      S,
    );
    // …and with no form left, its prototype-only handler goes too
    js = swapRe(js, /\n  \/\* "Notify me":[\s\S]*?\n  \}\);\n/, '\n', S);
  }
  write(path.join(SITE, 'js', name), js);
}

copyDir(path.join(FOLDER, 'img'), path.join(SITE, 'img'));
copyDir(path.join(FOLDER, 'fonts'), path.join(SITE, 'fonts'), (name) => name.endsWith('.woff2'));
copyDir(path.join(ROOT, 'src/assets/fonts'), path.join(SITE, 'fonts'), (name) => /^PPNeueMontreal-(Book|BookItalic|Medium|Semibold)\.woff2$/.test(name));
copyDir(path.join(ROOT, 'src/assets/landing'), path.join(SITE, 'landing'));

// ---- check what ships ----------------------------------------------------------------------------
if (!fs.existsSync(path.join(PUBLIC, 'og-v2.jpg'))) fail('public/og-v2.jpg (the social card the pages name) is missing');
const outputs = [
  path.join(SITE, 'home.html'),
  path.join(PUBLIC, 'extension/index.html'),
  path.join(PUBLIC, 'connect/index.html'),
  path.join(PUBLIC, 'iphone/index.html'),
  path.join(PUBLIC, 'contact/index.html'),
  path.join(PUBLIC, 'terms/index.html'),
  path.join(PUBLIC, 'privacy/index.html'),
  path.join(SITE, 'style.css'),
  ...fs.readdirSync(path.join(SITE, 'js')).map((name) => path.join(SITE, 'js', name)),
];
const leftovers = ['2026-10-06-stashe-homepage', 'src/assets', 'prototype: not sent', 'data-notify', 'class="review"', 'exploration v0', 'logo/favicon.svg'];
for (const file of outputs) {
  // The generated-from header names the prototype folder on purpose; everything else mustn't
  const text = read(file).split(GENERATED.slice(5, -4)).join('');
  for (const bad of leftovers) {
    if (text.includes(bad)) fail(`${path.relative(ROOT, file)} still contains ${JSON.stringify(bad)}`);
  }
  for (const [, ref] of text.matchAll(/["'(](\/site\/[^"')?#\s]+)/g)) {
    if (!fs.existsSync(path.join(PUBLIC, ref))) fail(`${path.relative(ROOT, file)} points at ${ref}, which wasn't published`);
  }
}
console.log(`publish-site: wrote the homepage, /extension (v${manifest.version}, ${zipKb} KB), /connect, /iphone, /contact, /terms, /privacy, and public/site/`);
